server:
  port: 8090

mongo:
  enabled: true

kafka:
  enabled: false

eureka:

  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

  instance:
    preferIpAddress: true

spring:

  zipkin:
    enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: giftly
      username:
      password:
