configserver:
  image: koko/giftly-config-server
  ports:
   - "6888:6888"
  restart: always

discovery:
  image: koko/giftly-discovery-service
  ports:
   - "8761:8761"
  restart: always

service:
  image: koko/giftly-service
  ports:
   - "7790-7799"
  links:
   - configserver
   - discovery
  restart: always

gateway:
  image: koko/giftly-gateway
  ports:
   - "8090:8090"
  links:
   - configserver
   - discovery
  restart: always

hystrix:
  image: koko/giftly-hystrix-dashboard
  ports:
   - "8010:8010"
  links:
   - gateway
   - discovery
  restart: always
