server:
  port: 4888

eureka:

  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

  instance:
    preferIpAddress: true

spring:
  zipkin:
    enabled: false

auth:
  token:
    secret: secret