spark-master:
  container_name: spark-master
  image: t3g7/docker-spark
  command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  hostname: spark-master
  environment:
    - "SPARK_CONF_DIR: /conf"
  expose:
    - 7003
    - 7004
    - 7005
    - 7006
    - 7007
    - 7078
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8550:8550
  volumes:
    - ./conf/master:/conf
    - ./data:/usr/local/spark/data

spark-slave:
  container_name: spark-slave
  image: t3g7/docker-spark
  command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  hostname: slave1
  environment:
    - "SPARK_CONF_DIR: /conf"
    - "SPARK_WORKER_CORES: 2"
    - "SPARK_WORKER_MEMORY: 2g"
    - "SPARK_WORKER_PORT: 8881"
    - "SPARK_WORKER_WEBUI_PORT: 8551"
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8551
  ports:
    - 8551:8551
  volumes:
    - ./conf/slave:/conf
    - ./data:/usr/local/spark/data
  links:
   - spark-master:spark-master
