server:
  port: 8020

eureka:

  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

  instance:
    preferIpAddress: true

spring:

  zipkin:
    enabled: false

aws:
  defaultRegion: {region}
  credentials:
    accessKey: {accessKey}
    secretKey: {secretKey}