zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"
  environment:
    SERVICE_NAME: giftlyzoo

kafka:
  image: wurstmeister/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
     KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
     KAFKA_ADVERTISED_HOST_NAME: "localhost"
     KAFKA_CREATE_TOPICS: "gifts:1:1,likes:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
